#### Examples

In [2]:
import numpy as np

arr = np.array([1,2,3,4])
arr

In [24]:
a = np.ones((100), dtype='int32')

a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [44]:
np.random.randint(6699999, size= (2,2))

array([[5623335, 4480313],
       [1105842, 2701497]])

In [47]:
4^2

6

In [9]:
import numpy as np
A = np.array([1,-9,34,56])

In [10]:
np.sort(A)

array([-9,  1, 34, 56])

#### Reading/ Loading from Text File

In [24]:
filedata = filedata.astype('int32')
np.sort(filedata)
filedata > 5

array([ True,  True,  True,  True,  True, False, False,  True])

###### Extract odd numbers from array

In [26]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

#####  Replace all odd numbers in arr with -1

In [37]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

 ##### How to replace items that satisfy a condition without affecting the original array?

In [41]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

out = np.where(arr%2 == 1, -1, arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

##### How to reshape an array?

In [45]:
arr = np.array([1, 2, 3, 4])
arr.reshape(2,-1)
# arr.reshape(2,2)

array([[1, 2],
       [3, 4]])

##### Generating random numbers in a given range

In [82]:
arr1 = np.array([1,2,3])

np.random.randint(10, size=(5,1))

array([[5],
       [9],
       [1],
       [8],
       [1]])